In [3]:
import pandas as pd
import functools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import numpy.random as nr
import math
from sklearn import preprocessing
import sklearn.model_selection as ms
from sklearn import linear_model
import sklearn.metrics as sklm

%matplotlib inline

In [4]:
works_custs = pd.read_csv('AdvWorksCusts.csv')
print(works_custs.shape)
print(works_custs.CustomerID.unique().shape)
bike_buyer = pd.read_csv('AW_BikeBuyer.csv')
print(bike_buyer.shape)
print(bike_buyer.CustomerID.unique().shape)
avemonth_spend = pd.read_csv('AW_AveMonthSpend.csv')
print(avemonth_spend.shape)
print(avemonth_spend.CustomerID.unique().shape)

(16519, 23)
(16404,)
(16519, 2)
(16404,)
(16519, 2)
(16404,)


In [5]:
(works_custs.astype(np.object) == 'NaN').any()

CustomerID              False
Title                   False
FirstName               False
MiddleName              False
LastName                False
Suffix                  False
AddressLine1            False
AddressLine2            False
City                    False
StateProvinceName       False
CountryRegionName       False
PostalCode              False
PhoneNumber             False
BirthDate               False
Education               False
Occupation              False
Gender                  False
MaritalStatus           False
HomeOwnerFlag           False
NumberCarsOwned         False
NumberChildrenAtHome    False
TotalChildren           False
YearlyIncome            False
dtype: bool

In [231]:
bike_buyer = pd.read_csv('AW_BikeBuyer.csv')
bike_buyer.drop_duplicates(subset = 'CustomerID', keep = 'last', inplace = True)
print(bike_buyer.columns)

Index(['CustomerID', 'BikeBuyer'], dtype='object')


In [6]:
works_custs.drop_duplicates(subset = 'CustomerID', keep = 'last', inplace = True)
bike_buyer.drop_duplicates(subset = 'CustomerID', keep = 'last', inplace = True)
avemonth_spend.drop_duplicates(subset = 'CustomerID', keep = 'last', inplace = True)
print(works_custs.shape)
print(bike_buyer.shape)
print(avemonth_spend.shape)

(16404, 23)
(16404, 2)
(16404, 2)


In [7]:
works_custs_bike_buyer = pd.merge(works_custs,bike_buyer, on='CustomerID')
merged_df = pd.merge(works_custs_bike_buyer,avemonth_spend, on='CustomerID')
merged_df.head(50)

CustomerID Title  FirstName MiddleName   LastName Suffix  \
0        11000   NaN        Jon          V       Yang    NaN   
1        11001   NaN     Eugene          L      Huang    NaN   
2        11002   NaN      Ruben        NaN     Torres    NaN   
3        11003   NaN    Christy        NaN        Zhu    NaN   
4        11004   NaN  Elizabeth        NaN    Johnson    NaN   
5        11005   NaN      Julio        NaN       Ruiz    NaN   
6        11006   NaN      Janet          G    Alvarez    NaN   
7        11007   NaN      Marco        NaN      Mehta    NaN   
8        11008   NaN        Rob        NaN    Verhoff    NaN   
9        11009   NaN    Shannon          C    Carlson    NaN   
10       11010   NaN  Jacquelyn          C     Suarez    NaN   
11       11011   NaN     Curtis        NaN         Lu    NaN   
12       11012   NaN     Lauren          M     Walker    NaN   
13       11013   NaN        Ian          M    Jenkins    NaN   
14       11014   NaN     Sydney        NaN    Bennett    NaN   
15       11015   NaN      Chloe        NaN      Young    NaN   
16       11016   NaN      Wyatt          L       Hill    NaN   
17       11019   NaN       Luke          L        Lal    NaN   
18       11020   NaN     Jordan          C       King    NaN   
19       11023   NaN       Seth          M    Edwards    NaN   
20       11024   NaN    Russell        NaN        Xie    NaN   
21       11025   NaN  Alejandro        NaN       Beck    NaN   
22       11026   NaN     Harold        NaN        Sai    NaN   
23       11027   NaN     Jessie          R       Zhao    NaN   
24       11028   NaN       Jill        NaN    Jimenez    NaN   
25       11031   NaN    Theresa          G      Ramos    NaN   
26       11032   NaN     Denise        NaN      Stone    NaN   
27       11033   NaN      Jaime        NaN       Nath    NaN   
28       11034   NaN      Ebony        NaN   Gonzalez    NaN   
29       11035   NaN      Wendy        NaN  Dominguez    NaN   
30       11036   NaN   Jennifer          C    Russell    NaN   
31       11037   NaN      Chloe          M     Garcia    NaN   
32       11040   NaN      Jesse        NaN     Murphy    NaN   
33       11042   NaN      Megan          J    Sanchez    NaN   
34       11043   NaN     Nathan          M    Simmons    NaN   
35       11044   NaN       Adam          L     Flores    NaN   
36       11045   NaN    Leonard          G       Nara    NaN   
37       11046   NaN  Christine        NaN       Yuan    NaN   
38       11047   NaN     Jaclyn          D         Lu    NaN   
39       11049   NaN      Carol          C        Rai    NaN   
40       11050   NaN       Alan        NaN      Zheng    NaN   
41       11051   NaN     Daniel        NaN    Johnson    NaN   
42       11052   NaN      Heidi        NaN      Lopez    NaN   
43       11053   NaN        Ana          E      Price    NaN   
44       11054   NaN     Deanna        NaN      Munoz    NaN   
45       11055   NaN    Gilbert        NaN       Raje    NaN   
46       11056   NaN    Michele          L       Nath    NaN   
47       11057   NaN       Carl          J   Andersen    NaN   
48       11058   NaN       Marc        NaN       Diaz    NaN   
49       11059   NaN     Ashlee          J   Andersen    NaN   

                 AddressLine1 AddressLine2            City StateProvinceName  \
0             3761 N. 14th St          NaN     Rockhampton        Queensland   
1                  2243 W St.          NaN         Seaford          Victoria   
2            5844 Linden Land          NaN          Hobart          Tasmania   
3            1825 Village Pl.          NaN      North Ryde   New South Wales   
4         7553 Harness Circle          NaN      Wollongong   New South Wales   
5         7305 Humphrey Drive          NaN   East Brisbane        Queensland   
6               2612 Berry Dr          NaN      Matraville   New South Wales   
7            942 Brook Street          NaN     Warrnambool          Victoria   
8            624 Pe

In [8]:
#help(pd.merge)
merged_df.dtypes

CustomerID               int64
Title                   object
FirstName               object
MiddleName              object
LastName                object
Suffix                  object
AddressLine1            object
AddressLine2            object
City                    object
StateProvinceName       object
CountryRegionName       object
PostalCode              object
PhoneNumber             object
BirthDate               object
Education               object
Occupation              object
Gender                  object
MaritalStatus           object
HomeOwnerFlag            int64
NumberCarsOwned          int64
NumberChildrenAtHome     int64
TotalChildren            int64
YearlyIncome             int64
BikeBuyer                int64
AveMonthSpend            int64
dtype: object

In [9]:
labels = np.array(merged_df['BikeBuyer'])
labels.size

16404

In [10]:
def encode_string(cat_features):
    ## First encode the strings to numeric categories
    enc = preprocessing.LabelEncoder()
    enc.fit(cat_features)
    enc_cat_features = enc.transform(cat_features)
    ## Now, apply one hot encoding
    ohe = preprocessing.OneHotEncoder()
    encoded = ohe.fit(enc_cat_features.reshape(-1,1))
    return encoded.transform(enc_cat_features.reshape(-1,1)).toarray()

categorical_columns = ['Education', 'Occupation', 'Gender', 'MaritalStatus']

Features = encode_string(merged_df['BikeBuyer'])
for col in categorical_columns:
    temp = encode_string(merged_df[col])
    Features = np.concatenate([Features, temp], axis = 1)

print(Features.shape)
print(Features[:2, :])    

(16404, 16)
[[1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 1.]]


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a Lab

In [11]:
#Features = np.concatenate([Features, np.array(aw_test_bikebuyer[['HomeOwnerFlag', 'NumberCarsOwned', 
#                            'NumberChildrenAtHome', 'YearlyIncome']])], axis = 1)
Features = np.concatenate([Features, np.array(merged_df[['NumberChildrenAtHome', 'YearlyIncome']])], axis = 1)
print(Features.shape)
print(Features[:2, :])  

(16404, 18)
[[1.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  0.00000e+00 1.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 1.37947e+05]
 [0.00000e+00 1.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  0.00000e+00 1.00000e+00 0.00000e+00 1.00000e+00 3.00000e+00 1.01141e+05]]


In [12]:
## Randomly sample cases to create independent training and test data
nr.seed(9988)
indx = range(Features.shape[0])
indx = ms.train_test_split(indx, test_size = 500) #need to have shuffle=False in here for correct answer
X_train = Features[indx[0],:]
y_train = np.ravel(labels[indx[0]])
#X_test = Features[indx[1],:]
#y_test = np.ravel(labels[indx[1]])

In [13]:
scaler = preprocessing.StandardScaler().fit(X_train[:,17:])
X_train[:,17:] = scaler.transform(X_train[:,17:])
#X_test[:,17:] = scaler.transform(X_test[:,17:])
X_train[:2,]

array([[ 1.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         1.        ,  0.        , -0.52751147],
       [ 1.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  1.        ,
         0.        ,  0.        , -0.44654991]])

In [14]:
#logistic_mod = linear_model.LogisticRegression() 
#logistic_mod.fit(X_train, y_train)

In [15]:
#print(logistic_mod.intercept_)
#print(logistic_mod.coef_)

In [16]:
#probabilities = logistic_mod.predict_proba(Features)
#print(probabilities[:15,:])

In [17]:
#def score_model(probs, threshold):
#    return np.array([1 if x > threshold else 0 for x in probs[:,1]])
#scores = score_model(probabilities, 0.5)
#print(np.array(scores[:500]))

In [18]:
# Start the test data prediction
aw_test = pd.read_csv('aw_test.csv')
aw_test.drop_duplicates(subset = 'CustomerID', keep = 'last', inplace = True)
print(aw_test.columns)

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome'],
      dtype='object')


In [19]:
labelsT = np.array(aw_test['Occupation'])
lavelsT.size()

NameError: name 'lavelsT' is not defined

In [20]:
def encode_string(cat_features):
    ## First encode the strings to numeric categories
    enc = preprocessing.LabelEncoder()
    enc.fit(cat_features)
    enc_cat_features = enc.transform(cat_features)
    ## Now, apply one hot encoding
    ohe = preprocessing.OneHotEncoder()
    encoded = ohe.fit(enc_cat_features.reshape(-1,1))
    return encoded.transform(enc_cat_features.reshape(-1,1)).toarray()

categorical_columns = ['Education', 'Gender', 'MaritalStatus']

FeaturesT = encode_string(aw_test['Occupation'])
for col in categorical_columns:
    tempT = encode_string(aw_test[col])
    FeaturesT = np.concatenate([FeaturesT, tempT], axis = 1)

print(FeaturesT.shape)
print(FeaturesT[:2, :])

(500, 14)
[[0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 1.]
 [0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 1. 1. 0.]]


/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a Lab

In [21]:
FeaturesT = np.concatenate([FeaturesT, np.array(aw_test[['HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'YearlyIncome']])], axis = 1)
#FeaturesT = np.concatenate([Features, np.array(aw_test[['HomeOwnerFlag', 'NumberCarsOwned', 'NumberChildrenAtHome', 'YearlyIncome']])], axis = 1)
print(FeaturesT.shape)
print(FeaturesT[:2, :]) 

(500, 18)
[[0.00000e+00 1.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 0.00000e+00
  0.00000e+00 1.00000e+00 0.00000e+00 2.00000e+00 0.00000e+00 8.69310e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00 1.00000e+00
  0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 0.00000e+00 1.00000e+00
  1.00000e+00 0.00000e+00 1.00000e+00 2.00000e+00 2.00000e+00 1.00125e+05]]


In [22]:
## Randomly sample cases to create independent training and test data
nr.seed(9988)
indx = range(FeaturesT.shape[0])
indx = ms.train_test_split(indx, test_size = 499, shuffle=False) #need to have shuffle=False in here for correct answer
#X_train = FeaturesT[indx[0],:]
#y_train = np.ravel(labelsT[indx[0]])
X_test = FeaturesT[indx[1],:]
y_test = np.ravel(labelsT[indx[1]])

In [23]:
scaler = preprocessing.StandardScaler().fit(X_train[:,17:])
#X_train[:,16:] = scaler.transform(X_train[:,16:])
X_test[:,17:] = scaler.transform(X_test[:,17:])
#X_train[:2,]

In [24]:
logistic_mod = linear_model.LogisticRegression() 
logistic_mod.fit(X_train, y_train)

/anaconda3/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [25]:
print(logistic_mod.intercept_)
print(logistic_mod.coef_)

[-0.26951155]
[[-6.90673334  6.63722179  0.07264017  0.01513166 -0.12311974 -0.05429136
  -0.17987228 -0.04919292 -0.29294805  0.01524023  0.01081282  0.04657636
  -0.27822726  0.00871571 -0.48253394  0.21302239  0.34348087  0.21826408]]


In [26]:
print(FeaturesT)

[[0.00000e+00 1.00000e+00 0.00000e+00 ... 2.00000e+00 0.00000e+00
  8.69310e+04]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 2.00000e+00 2.00000e+00
  1.00125e+05]
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 2.00000e+00 0.00000e+00
  1.03985e+05]
 ...
 [0.00000e+00 1.00000e+00 0.00000e+00 ... 4.00000e+00 3.00000e+00
  1.38097e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 1.00000e+00 0.00000e+00
  1.01465e+05]
 [0.00000e+00 0.00000e+00 0.00000e+00 ... 2.00000e+00 0.00000e+00
  1.91080e+04]]


In [35]:
probabilities = logistic_mod.predict_proba(X_test)
print(probabilities[:15,:])

[[0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [36]:
def score_model(probs, threshold):
    return np.array([1 if x > threshold else 0 for x in probs[:,1]])
scores = score_model(probabilities, 0.5)
print(np.array(scores[:500]))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 

In [31]:
df = pd.DataFrame(FeaturesT)
df.head()

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0   
1  0.0  0.0  0.0  0.0  1.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0   
2  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0   
3  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  1.0   
4  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0   

    15   16        17  
0  2.0  0.0   86931.0  
1  2.0  2.0  100125.0  
2  2.0  0.0  103985.0  
3  0.0  0.0  127161.0  
4  1.0  2.0   21876.0

In [32]:
df.to_csv('aw_test_prediction2.csv')